###
PATCH http://localhost:3000/api/v1/fetch/brand/brand_id/135
Content-Type: application/json

{
    "brand_name": "Samsung",
    "brand_logo_path": "none",
    "brand_website": "https://www.samsung.com/"
}
