###
PATCH http://localhost:3000/api/v1/fetch/brand/brand_id/134
Content-Type: application/json

{
    "brand_name": "Apple",
    "brand_logo_path": "https://www.apple.com/ac/structured-data/images/knowledge_graph_logo.png?202106302340",
    "brand_website": "https://www.apple.com/",
    "brand_country_make": "USA"
}

###
GET http://localhost:3000/api/v1/fetch/brand/


{
    "avatarUrl": "https://www.apple.com/ac/structured-data/images/knowledge_graph_logo.png?202106302340",
}

###
POST http://localhost:3000/api/v1/user/login/
Content-Type: application/json

{
    "user_email": "rodojml@me.com",
    "user_password": "rjml2290"
}


###
GET http://localhost:3000/api/v1/listing/getAll_previews

###
GET http://localhost:3000/api/v1/listing/previews?page=2&pageSize=2

###
GET http://localhost:3000/api/v1/fetch/sizes


###
GET http://localhost:3000/api/v1/listing/previews?key=panerai%20luminor&page=1&pageSize=2

###
GET http://localhost:3000/api/v1/listing/guestHasListing?key=60002031

###
POST http://localhost:3000/api/v1/user/add_unregistered_user/
Content-Type: application/json

{
    "date": "any",
    "description": "any",
    "name": "java",
    "lastName": "hutt",
    "user_id": 60002032,
    "user_email": "javathehutt@lucas.com",
    "cprice": 200000,
    "dprice": 200000,
    "warranty": 3
}